# Generated by Django 5.0.4 on 2024-04-07 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_comment='设备id', default=uuid.uuid4, editable=False, verbose_name='设备id')),
                ('name', models.CharField(db_comment='设备名称', max_length=32, verbose_name='设备名称')),
                ('description', models.CharField(db_comment='设备描述', max_length=255, null=True, verbose_name='设备描述')),
                ('hostname', models.CharField(db_comment='主机名', max_length=32, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(db_comment='设备ip', unique=True, verbose_name='设备ip')),
                ('login', models.CharField(db_comment='登录方式', max_length=32, verbose_name='登录方式')),
                ('url', models.CharField(db_comment='网址', max_length=128, null=True, verbose_name='网址')),
                ('username', models.CharField(db_comment='账号', max_length=32, verbose_name='账号')),
                ('password', models.CharField(db_comment='密码', max_length=64, verbose_name='密码')),
                ('remark', models.TextField(db_comment='备注', null=True, verbose_name='备注')),
                ('snmp_id', models.IntegerField(db_comment='snmp模板id', default=1, verbose_name='snmp模板id')),
                ('company_id', models.IntegerField(db_comment='设备厂商id', default=1, verbose_name='设备厂商id')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备表',
                'verbose_name_plural': '设备表',
                'db_table': 'device',
                'db_table_comment': '设备模型',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment='厂家代码', max_length=32, verbose_name='厂家代码')),
                ('name', models.CharField(db_comment='厂家名称', max_length=32, verbose_name='厂家名称')),
                ('model', models.CharField(db_comment='设备型号', max_length=32, verbose_name='设备型号')),
            ],
            options={
                'verbose_name': '设备厂家信息',
                'verbose_name_plural': '设备厂家信息',
                'db_table': 'device_company',
                'db_table_comment': '设备厂家信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_comment='设备id', editable=False, verbose_name='设备id')),
                ('ifIndex', models.IntegerField(db_comment='接口索引', verbose_name='接口索引')),
                ('ifDescr', models.CharField(db_comment='描述接口的字符串', max_length=32, verbose_name='描述接口的字符串')),
                ('ifPhysAddress', models.CharField(db_comment='MAC地址', max_length=32, verbose_name='MAC地址')),
                ('ifOperStatus', models.IntegerField(db_comment='接口当前的状态', verbose_name='接口当前的状态')),
                ('ifName', models.CharField(db_comment='接口名', max_length=32, verbose_name='接口名')),
                ('ifAlias', models.CharField(db_comment='接口别名', max_length=32, verbose_name='接口别名')),
                ('ifHighSpeed', models.IntegerField(db_comment='接口当前带宽', verbose_name='接口当前带宽')),
            ],
            options={
                'verbose_name': '设备接口',
                'verbose_name_plural': '设备接口',
                'db_table': 'device_interface',
                'db_table_comment': '设备接口',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_comment='设备id', editable=False, verbose_name='设备id')),
                ('ipAdEntAddr', models.GenericIPAddressField(db_comment='IP地址', verbose_name='IP地址')),
                ('ipAdEntIfIndex', models.IntegerField(db_comment='接口的索引值', verbose_name='接口的索引值')),
                ('ipAdEntNetMask', models.GenericIPAddressField(db_comment='子网掩码', verbose_name='子网掩码')),
            ],
            options={
                'verbose_name': '设备ip',
                'verbose_name_plural': '设备ip',
                'db_table': 'device_ip',
                'db_table_comment': '设备ip',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_comment='设备id', editable=False, verbose_name='设备id')),
                ('entPhysicalSoftwareRev', models.CharField(db_comment='软件版本号', max_length=128, verbose_name='软件版本号')),
                ('entPhysicalSerialNum', models.CharField(db_comment='序列号', max_length=128, verbose_name='序列号')),
                ('entPhysicalDescr', models.CharField(db_comment='物理实体描述信息', max_length=128, verbose_name='物理实体描述信息')),
            ],
            options={
                'verbose_name': '设备系统信息',
                'verbose_name_plural': '设备系统信息',
                'db_table': 'device_serial',
                'db_table_comment': '设备系统信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_comment='设备id', editable=False, verbose_name='设备id')),
                ('sysDescr', models.CharField(db_comment='系统的文字描述', max_length=128, verbose_name='系统的文字描述')),
                ('sysUpTime', models.IntegerField(db_comment='运行的时间', verbose_name='运行的时间')),
                ('sysName', models.CharField(db_comment='hostname', max_length=128, verbose_name='hostname')),
            ],
            options={
                'verbose_name': '设备系统信息',
                'verbose_name_plural': '设备系统信息',
                'db_table': 'device_system',
                'db_table_comment': '设备系统信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SnmpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='模板名', max_length=32, verbose_name='模板名')),
                ('version', models.IntegerField(db_comment='版本', default=2, verbose_name='版本')),
                ('community', models.CharField(db_comment='团体字', default='public', max_length=32, verbose_name='团体字')),
                ('username', models.CharField(db_comment='用户名', default='user', max_length=32, verbose_name='用户名')),
                ('password', models.CharField(db_comment='密码', default='pass', max_length=32, verbose_name='密码')),
                ('auth_protocol', models.CharField(db_comment='认证协议', default='MD5', max_length=32, verbose_name='认证协议')),
                ('security_level', models.CharField(db_comment='认证级别', default='noAuthNoPriv', max_length=32, verbose_name='认证级别')),
                ('privacy_protocol', models.CharField(db_comment='私有协议', default='DES', max_length=32, verbose_name='私有协议')),
                ('privacy_password', models.CharField(db_comment='私有密码', default='otherPass', max_length=32, verbose_name='私有密码')),
                ('context', models.CharField(db_comment='上下文', default='context', max_length=32, verbose_name='上下文')),
            ],
            options={
                'verbose_name': 'snmp模板',
                'verbose_name_plural': 'snmp模板',
                'db_table': 'device_snmp_template',
                'db_table_comment': 'snmp模板',
                'ordering': ['id'],
            },
        ),
    ]
